### ISSUE TITLE
how to put up a poll via api again after updating to 2.0?

### ISSUE THREAD

**Issue by Amannda123** [sampaiodiego/rocket.chat.app-poll#57]
Hi, 

havent updated in a long time (just switched from RC 2.x to 3.x) and now since a couple of days my poll that im creating via a cron job daily isnt working anymore :(

Any ways to do enable that again?

**Comment by sampaiodiego** [comment]
can you please show an example of what you have been doing so far? it wasn't clear to me if you were using a REST endpoint to create a poll, is that the case? if so, can you please show the payload you were using? thx

**Comment by Amannda123** [comment]
Hi, doing it like this in crontab -e 
might be not the finest.. but it worked =) im sure im just missing another option since the latest updates... 

`0 0 * * 1-5 curl -H "X-Auth-Token: TOKEN" -H "X-User-Id: 8LQvGs2E9Mx34iykF" -H "Content-type: application/json" https://server.foo/api/v1/commands.run -d '{"command":"poll","roomId":"nNKi2sahKf4ETzg8K","params":"\"Question:\" \"Option1\" \"Option2\" \"Option3\" \"Option4\" \"Option5\" \"Option6\" \"Option7\" \"Option8\""}' >/dev/null 2>&1`

**Comment by sampaiodiego** [comment]
thanks @Amannda123 .. actually the command payload changed and it is not possible anymore to create a poll with the command only, it currently requires you to interact with the form on the modal it opens.

we're discussing about this on https://github.com/sampaiodiego/rocket.chat.app-poll/issues/47 .. I'll close this issue as duplicated of that one, since you want the same thing.. I'll try to find a good solution for it.
